# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usict', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=200, unique='True'),
        ),
    ]
