# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usict', '0005_auto_20171010_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
